<?php
$inpupon='
 oninput="realizaProcesos' . $idfila . '(
                
    $(' . $aster . '#jfndhom' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#costoxcaj' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#costo' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#modobus' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#buscar' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#nref' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#fecven' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#agrstock' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#descuento' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#iibb_bsas' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#iibb_caba' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#perc_iva' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#iva' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#desadi' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#costo_final' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mka' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mga' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpa' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mkb' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#mub' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#mgb' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpb' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mkc' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#muc' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#mgc' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpc' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mkd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mud' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mgd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mke' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mue' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mge' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpe' . $idfila . '' . $aster . ').val(),                         
    $(' . $aster . '#eka' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#ega' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#epa' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#ekb' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#eub' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#egb' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#epb' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#ekc' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#euc' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#egc' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#epc' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#ekd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#eud' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#egd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#epd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#eke' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#eue' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#ege' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#epe' . $idfila . '' . $aster . ').val()
    
); ajax_preciomayorista' . $idfila . '(            
    $(' . $aster . '#idcosto' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#jfndhom' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#costo_final' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mka' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mga' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpa' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mkb' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#mub' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#mgb' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpb' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mkc' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#muc' . $idfila . '' . $aster . ').val(),            
    $(' . $aster . '#mgc' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpc' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mkd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mud' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mgd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpd' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mke' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mue' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mge' . $idfila . '' . $aster . ').val(),
    $(' . $aster . '#mpe' . $idfila . '' . $aster . ').val()                                                
    ); 
    ajax_precioespeciales' . $idfila . '( 
        $(' . $aster . '#idcosto' . $idfila . '' . $aster . ').val(),           
        $(' . $aster . '#jfndhom' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#costo_final' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#eka' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#ega' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#epa' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#ekb' . $idfila . '' . $aster . ').val(),            
        $(' . $aster . '#eub' . $idfila . '' . $aster . ').val(),            
        $(' . $aster . '#egb' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#epb' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#ekc' . $idfila . '' . $aster . ').val(),            
        $(' . $aster . '#euc' . $idfila . '' . $aster . ').val(),            
        $(' . $aster . '#egc' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#epc' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#ekd' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#eud' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#egd' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#epd' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#eke' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#eue' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#ege' . $idfila . '' . $aster . ').val(),
        $(' . $aster . '#epe' . $idfila . '' . $aster . ').val()                                               
        )";';
 
?>